services:
  sharetext.webapi:
    image: sharetext.webapi
    build:
      context: .
      dockerfile: ShareText.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo:8.0
    container_name: sharetext.db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
